//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddresses
    {
        public int AddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int CityID { get; set; }
        public string ZipCode { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Users Users { get; set; }
    }
}
